### ISSUE TITLE
Generated pyproject.toml is invalid

### ISSUE THREAD

**Issue by paolodina** [python-ellar/ellar-cli#78]
The error is shown in VS Code from the linter.

> Additional properties are not allowed ('ellar' was unexpected)Even Better TOML

![pyproject toml](https://github.com/python-ellar/ellar-cli/assets/1157401/cdd2f184-d527-477c-bda9-05c371ae4dfe)

The file *is* parseable:

```python
In [1]: from tomlkit import parse

In [2]: foo="""
   ...: [ellar]
   ...: default = "new_project"
   ...: """

In [3]: parse(foo)
Out[3]: {'ellar': {'default': 'new_project'}}
```

but trying with [validate-pyproject](https://github.com/abravalheri/validate-pyproject) the error again.

```bash
$ validate-pyproject pyproject.toml 
Invalid file: pyproject.toml
[ERROR] `data` must not contain {'ellar'} properties
```

Not sure if it's a real problem, though `ellar-cli` relies on this nomenclature in `pyproject.toml` to handle the multi-project if I'm not mistaken.

**Comment by eadwinCode** [comment]
Yes @paolodina you are right. The EllarCLI depends on pyproject.toml to handle multiple-projects. 

On the linting error, I am using the tomlkit package to write to project.toml file but I will take a look at it to know why it's showing errors on VS code cause it doesn't show on pycharm.

**Comment by eadwinCode** [comment]
I will also use this validate-pyproject to ensure everything works fine

**Comment by eadwinCode** [comment]
@paolodina Can you close this if the latest update fixes the issue?

**Comment by paolodina** [comment]
Of course @eadwinCode, I read the patch when you did it but forgot to close the issue.
